name: Markdown Lint

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  markdown-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli

      - name: Run markdownlint
        run: markdownlint "**/*.md" "**/*.markdown" --config .markdownlint.json --ignore "_site/**"
